iso_alpha_dict = {'Afghanistan': 'AFG', 'Albania': 'ALB', 'Algeria': 'DZA', 'Angola': 'AGO', 'Argentina': 'ARG',
                  'Australia': 'AUS', 'Austria': 'AUT', 'Bahrain': 'BHR', 'Bangladesh': 'BGD', 'Belgium': 'BEL',
                  'Benin': 'BEN', 'Bolivia': 'BOL', 'Bosnia and Herzegovina': 'BIH', 'Botswana': 'BWA', 'Brazil': 'BRA',
                  'Bulgaria': 'BGR', 'Burkina Faso': 'BFA', 'Burundi': 'BDI', 'Cambodia': 'KHM', 'Cameroon': 'CMR',
                  'Canada': 'CAN', 'Central African Republic': 'CAF', 'Chad': 'TCD', 'Chile': 'CHL', 'China': 'CHN',
                  'Colombia': 'COL', 'Comoros': 'COM', 'Congo, Dem. Rep.': 'COD', 'Congo, Rep.': 'COG',
                  'Costa Rica': 'CRI', "Cote d'Ivoire": 'CIV', 'Croatia': 'HRV', 'Cuba': 'CUB', 'Czech Republic': 'CZE',
                  'Denmark': 'DNK', 'Djibouti': 'DJI', 'Dominican Republic': 'DOM', 'Ecuador': 'ECU', 'Egypt': 'EGY',
                  'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ', 'Eritrea': 'ERI', 'Ethiopia': 'ETH',
                  'Finland': 'FIN', 'France': 'FRA', 'Gabon': 'GAB', 'Gambia': 'GMB', 'Germany': 'DEU', 'Ghana': 'GHA',
                  'Greece': 'GRC', 'Guatemala': 'GTM', 'Guinea': 'GIN', 'Guinea-Bissau': 'GNB', 'Haiti': 'HTI',
                  'Honduras': 'HND', 'Hong Kong, China': 'HKG', 'Hungary': 'HUN', 'Iceland': 'ISL', 'India': 'IND',
                  'Indonesia': 'IDN', 'Iran': 'IRN', 'Iraq': 'IRQ', 'Ireland': 'IRL', 'Israel': 'ISR', 'Italy': 'ITA',
                  'Jamaica': 'JAM', 'Japan': 'JPN', 'Jordan': 'JOR', 'Kenya': 'KEN', 'Korea, Dem. Rep.': 'KOR',
                  'South Korea': 'KOR', 'Kuwait': 'KWT', 'Lebanon': 'LBN', 'Lesotho': 'LSO', 'Liberia': 'LBR',
                  'Libya': 'LBY', 'Madagascar': 'MDG', 'Malawi': 'MWI', 'Malaysia': 'MYS', 'Mali': 'MLI',
                  'Mauritania': 'MRT', 'Mauritius': 'MUS', 'Mexico': 'MEX', 'Mongolia': 'MNG', 'Montenegro': 'MNE',
                  'Morocco': 'MAR', 'Mozambique': 'MOZ', 'Myanmar': 'MMR', 'Namibia': 'NAM', 'Nepal': 'NPL',
                  'Netherlands': 'NLD', 'New Zealand': 'NZL', 'Nicaragua': 'NIC', 'Niger': 'NER', 'Nigeria': 'NGA',
                  'Norway': 'NOR', 'Oman': 'OMN', 'Pakistan': 'PAK', 'Panama': 'PAN', 'Paraguay': 'PRY', 'Peru': 'PER',
                  'Philippines': 'PHL', 'Poland': 'POL', 'Portugal': 'PRT', 'Puerto Rico': 'PRI', 'Reunion': 'REU',
                  'Romania': 'ROU', 'Rwanda': 'RWA', 'Sao Tome and Principe': 'STP', 'Saudi Arabia': 'SAU',
                  'Senegal': 'SEN', 'Serbia': 'SRB', 'Sierra Leone': 'SLE', 'Singapore': 'SGP',
                  'Slovak Republic': 'SVK', 'Slovenia': 'SVN', 'Somalia': 'SOM', 'South Africa': 'ZAF', 'Spain': 'ESP',
                  'Sri Lanka': 'LKA', 'Sudan': 'SDN', 'Swaziland': 'SWZ', 'Sweden': 'SWE', 'Switzerland': 'CHE',
                  'Syria': 'SYR', 'Taiwan': 'TWN', 'Tanzania': 'TZA', 'Thailand': 'THA', 'Togo': 'TGO',
                  'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN', 'Turkey': 'TUR', 'Uganda': 'UGA',
                  'United Kingdom': 'GBR', 'United States': 'USA', 'Uruguay': 'URY', 'Venezuela': 'VEN',
                  'Vietnam': 'VNM', 'West Bank and Gaza': 'PSE', 'Yemen, Rep.': 'YEM', 'Zambia': 'ZMB',
                  'Zimbabwe': 'ZWE', 'Bermuda': 'BMU', 'Lithuania': 'LTU', 'Hong Kong': 'HKG',
                  'United Arab Emirates': 'ARE', 'Seychelles': 'SYC', 'Estonia': 'EST', 'Uzbekistan': 'UZB',
                  'Luxembourg': 'LUX', 'Malta': 'MLT', 'Cayman Islands': 'CYM', 'Liechtenstein': 'LIE'}

continents_dict = {'Afghanistan': 'Asia', 'Albania': 'Europe', 'Algeria': 'Africa', 'Angola': 'Africa',
                   'Argentina': 'Americas', 'Australia': 'Oceania', 'Austria': 'Europe', 'Bahrain': 'Asia',
                   'Bangladesh': 'Asia', 'Belgium': 'Europe', 'Benin': 'Africa', 'Bolivia': 'Americas',
                   'Bosnia and Herzegovina': 'Europe', 'Botswana': 'Africa', 'Brazil': 'Americas', 'Bulgaria': 'Europe',
                   'Burkina Faso': 'Africa', 'Burundi': 'Africa', 'Cambodia': 'Asia', 'Cameroon': 'Africa',
                   'Canada': 'Americas', 'Central African Republic': 'Africa', 'Chad': 'Africa', 'Chile': 'Americas',
                   'China': 'Asia', 'Colombia': 'Americas', 'Comoros': 'Africa', 'Congo, Dem. Rep.': 'Africa',
                   'Congo, Rep.': 'Africa', 'Costa Rica': 'Americas', "Cote d'Ivoire": 'Africa', 'Croatia': 'Europe',
                   'Cuba': 'Americas', 'Czech Republic': 'Europe', 'Denmark': 'Europe', 'Djibouti': 'Africa',
                   'Dominican Republic': 'Americas', 'Ecuador': 'Americas', 'Egypt': 'Africa',
                   'El Salvador': 'Americas', 'Equatorial Guinea': 'Africa', 'Eritrea': 'Africa', 'Ethiopia': 'Africa',
                   'Finland': 'Europe', 'France': 'Europe', 'Gabon': 'Africa', 'Gambia': 'Africa', 'Germany': 'Europe',
                   'Ghana': 'Africa', 'Greece': 'Europe', 'Guatemala': 'Americas', 'Guinea': 'Africa',
                   'Guinea-Bissau': 'Africa', 'Haiti': 'Americas', 'Honduras': 'Americas', 'Hong Kong, China': 'Asia',
                   'Hungary': 'Europe', 'Iceland': 'Europe', 'India': 'Asia', 'Indonesia': 'Asia', 'Iran': 'Asia',
                   'Iraq': 'Asia', 'Ireland': 'Europe', 'Israel': 'Asia', 'Italy': 'Europe', 'Jamaica': 'Americas',
                   'Japan': 'Asia', 'Jordan': 'Asia', 'Kenya': 'Africa', 'Korea, Dem. Rep.': 'Asia',
                   'South Korea': 'Asia', 'Kuwait': 'Asia', 'Lebanon': 'Asia', 'Lesotho': 'Africa', 'Liberia': 'Africa',
                   'Libya': 'Africa', 'Madagascar': 'Africa', 'Malawi': 'Africa', 'Malaysia': 'Asia', 'Mali': 'Africa',
                   'Mauritania': 'Africa', 'Mauritius': 'Africa', 'Mexico': 'Americas', 'Mongolia': 'Asia',
                   'Montenegro': 'Europe', 'Morocco': 'Africa', 'Mozambique': 'Africa', 'Myanmar': 'Asia',
                   'Namibia': 'Africa', 'Nepal': 'Asia', 'Netherlands': 'Europe', 'New Zealand': 'Oceania',
                   'Nicaragua': 'Americas', 'Niger': 'Africa', 'Nigeria': 'Africa', 'Norway': 'Europe', 'Oman': 'Asia',
                   'Pakistan': 'Asia', 'Panama': 'Americas', 'Paraguay': 'Americas', 'Peru': 'Americas',
                   'Philippines': 'Asia', 'Poland': 'Europe', 'Portugal': 'Europe', 'Puerto Rico': 'Americas',
                   'Reunion': 'Africa', 'Romania': 'Europe', 'Rwanda': 'Africa', 'Sao Tome and Principe': 'Africa',
                   'Saudi Arabia': 'Asia', 'Senegal': 'Africa', 'Serbia': 'Europe', 'Sierra Leone': 'Africa',
                   'Singapore': 'Asia', 'Slovak Republic': 'Europe', 'Slovenia': 'Europe', 'Somalia': 'Africa',
                   'South Africa': 'Africa', 'Spain': 'Europe', 'Sri Lanka': 'Asia', 'Sudan': 'Africa',
                   'Swaziland': 'Africa', 'Sweden': 'Europe', 'Switzerland': 'Europe', 'Syria': 'Asia',
                   'Taiwan': 'Asia', 'Tanzania': 'Africa', 'Thailand': 'Asia', 'Togo': 'Africa',
                   'Trinidad and Tobago': 'Americas', 'Tunisia': 'Africa', 'Turkey': 'Europe', 'Uganda': 'Africa',
                   'United Kingdom': 'Europe', 'United States': 'Americas', 'Uruguay': 'Americas',
                   'Venezuela': 'Americas', 'Vietnam': 'Asia', 'West Bank and Gaza': 'Asia', 'Yemen, Rep.': 'Asia',
                   'Zambia': 'Africa', 'Zimbabwe': 'Africa', 'Bermuda': 'Americas', 'Lithuania': 'Europe',
                   'Hong Kong': 'Asia', 'United Arab Emirates': 'Asia', 'Seychelles': 'Africa', 'Estonia': 'Europe',
                   'Uzbekistan': 'Asia', 'Luxembourg': 'Europe', 'Malta': 'Europe', 'Cayman Islands': 'Americas',
                   'Liechtenstein': 'Europe'}
